# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20161228_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 28, 3, 26, 47, 291599, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
