# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
